name: Build IG
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ghcr.io/miracum/ig-build-tools:v2.2.8@sha256:2d07188c790822f2280e6b1863dc8051a70ec30463c075817deac8be27c691bd
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: build ig
        working-directory: PseudonymizationIG/
        run: |
          java -jar /usr/local/bin/publisher.jar -ig ig.ini
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: "PseudonymizationIG/output"

  deploy:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    container: ghcr.io/miracum/ig-build-tools:v2.2.8@sha256:2d07188c790822f2280e6b1863dc8051a70ec30463c075817deac8be27c691bd
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
